# Link repository with Travis CI
# https://travis-ci.org/

# Whitelist gh-pages branch
branches:
  only:
    - master

# Set the language
language: go

# Install hugo
install: go get -v github.com/spf13/hugo

# Attempt to build in public directory
script:
  - hugo -d public
