# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "MIMIC Data"
license = "MIT"
licenselink = "https://github.com/MIT-LCP/mimic-website/blob/master/themes/mimic-data/LICENSE.md"
description = "Website for the MIMIC Critical Care Dataset"
homepage = "http://mimic.physionet.org/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Tom Pollard"
  homepage = "http://tomp.io"

# If porting an existing theme
[original]
  name = "Steve Francia"
  homepage = "https://spf13.com"
  repo = "https://github.com/spf13/hugo"
